dist: xenial
notifications: {email: false}

env: [NODE_OPTIONS="--experimental-modules --no-warnings"]
language: node_js
node_js: node

install: npm install
script: npm test
after_success: npm run-script coverage
