name: reverse_proxy
version: 10.0.0

author: Cédric Belin <cedric@belin.io>
description: Simple reverse proxy server supporting WebSockets.
documentation: https://dev.belin.io/reverse-proxy/api
homepage: https://dev.belin.io/reverse-proxy

environment:
  sdk: '>=2.1.0 <3.0.0'

executables:
  reverse-proxy: reverse_proxy

dependencies:
  build_cli_annotations: ^1.0.1
  nodejs_interop: ^0.10.0
  yaml: ^2.1.15

dependency_overrides:
  nodejs_interop: {path: ../../dart/nodejs-interop.dart}

dev_dependencies:
  build_cli: ^1.0.2
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_version: ^2.0.0
  coverage: ^0.12.3
  grinder: ^0.8.3
  test: ^1.5.1
