site_name: Reverse-Proxy.js
site_description: Personal reverse proxy server supporting WebSockets, implemented in TypeScript.
site_author: Cédric Belin - cedric@belin.io
site_url: https://docs.belin.io/reverse-proxy.js

docs_dir: ../doc
site_dir: ../www

repo_name: git.belin.io
repo_url: https://git.belin.io/cedx/reverse-proxy.js
edit_uri: ""

copyright: Copyright &copy; 2014 - 2020 Cédric Belin
extra:
  social:
    - icon: fontawesome/solid/globe
      link: "https://belin.io"
      name: Belin.io
    - icon: fontawesome/brands/github
      link: "https://github.com/cedx"
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/cedxbelin"
      name: Twitter
    - icon: fontawesome/brands/linkedin
      link: "https://linkedin.com/in/cedxbelin"
      name: LinkedIn

extra_css:
  - css/mkdocs.css

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true

nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage:
      - Command line interface: usage/cli.md
      - Configuration: usage/configuration.md
      - Stand-alone proxy server: usage/standalone_server.md
      - Using HTTPS: usage/using_https.md
      - Hostname routing: usage/hostname_routing.md
      - Listening on multiple ports: usage/multiple_ports.md
      - Custom HTTP headers: usage/http_headers.md
  - About:
      - License: about/license.md
      - See also: about/see_also.md

theme:
  favicon: img/favicon.ico
  features:
    - instant
  icon:
    logo: fontawesome/solid/book-reader
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    accent: yellow
    primary: yellow
